/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view.frame;

import com.controller.DoUongController;
import com.handle.ImageHandle;
import com.handle.LanguageHandle;
import com.models.DataContext;
import com.models.DoUongModel;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dang
 */
public class DoUongFrame extends javax.swing.JFrame {

    DefaultTableModel modelttKH;

    /**
     * Creates new form KhachHangFrame
     */
    public DoUongFrame() {
        initComponents();
        loadText();
        configComponents();
        loadTable();
    }

    private void loadText() {
        TITLE = LanguageHandle.getInstance().getValue("Drinks", "TITLE");
        UPDATE = LanguageHandle.getInstance().getValue("Drinks", "UPDATE");
        RESET = LanguageHandle.getInstance().getValue("Drinks", "RESET");
        EXIT = LanguageHandle.getInstance().getValue("Drinks", "EXIT");
        REFRESH = LanguageHandle.getInstance().getValue("Drinks", "REFRESH");
        DELETE = LanguageHandle.getInstance().getValue("Drinks", "DELETE");
        NOTE = LanguageHandle.getInstance().getValue("Drinks", "NOTE");
        PRICE = LanguageHandle.getInstance().getValue("Drinks", "PRICE");
        IMAGE = LanguageHandle.getInstance().getValue("Drinks", "IMAGE");
        INFO = LanguageHandle.getInstance().getValue("Drinks", "INFO");
        ID = LanguageHandle.getInstance().getValue("Drinks", "ID");
        NAME = LanguageHandle.getInstance().getValue("Drinks", "NAME");
        ERR_NAME_EMPTY = LanguageHandle.getInstance().getValue("Drinks", "ERR_NAME_EMPTY");
        ERR_PRICE_EMPTY = LanguageHandle.getInstance().getValue("Drinks", "ERR_PRICE_EMPTY");
        NOTIFICATION_TITLE = LanguageHandle.getInstance().getValue("Drinks", "NOTIFICATION_TITLE");
        NOTI_SUCCESS = LanguageHandle.getInstance().getValue("Drinks", "NOTI_SUCCESS");
        NOTI_FAILED = LanguageHandle.getInstance().getValue("Drinks", "NOTI_FAILED");
        CHOSSE_DELETE = LanguageHandle.getInstance().getValue("Drinks", "CHOSSE_DELETE");
        REQUEST_DELETE = LanguageHandle.getInstance().getValue("Drinks", "REQUEST_DELETE");
        CHOSSE_FILE = LanguageHandle.getInstance().getValue("Drinks", "CHOSSE_FILE");
        ADD = LanguageHandle.getInstance().getValue("Drinks", "ADD");
    }

    private void configComponents() {
        setIconImage(ImageHandle.getInstance().getIconLogo());
        setTitle(TITLE);
        btnCapNhap.setText(UPDATE);
        btnReset.setText(REFRESH);
        btnXoa.setText(DELETE);
        btnThem.setText(ADD);

        lbGhiChu.setText(NOTE);
        lbGia.setText(PRICE);
        lbHinhAnh.setText(IMAGE);
        lbInfo.setText(INFO);
        lbMaDU.setText(ID);
        lbTenDU.setText(NAME);

        txtGia.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9')
                        || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lbMaDU = new javax.swing.JLabel();
        lbTenDU = new javax.swing.JLabel();
        lbGia = new javax.swing.JLabel();
        lbHinhAnh = new javax.swing.JLabel();
        txtMaDU = new javax.swing.JTextField();
        txtTenDU = new javax.swing.JTextField();
        lbGhiChu = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnCapNhap = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        lbIcon = new javax.swing.JLabel();
        lbInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbThongTinDU = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(228, 207, 203));
        jPanel3.setForeground(new java.awt.Color(97, 55, 47));

        lbMaDU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbMaDU.setForeground(new java.awt.Color(97, 55, 47));
        lbMaDU.setText("Mã Đồ Uống ");

        lbTenDU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTenDU.setForeground(new java.awt.Color(97, 55, 47));
        lbTenDU.setText("Tên Đồ Uống ");

        lbGia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbGia.setForeground(new java.awt.Color(97, 55, 47));
        lbGia.setText("Giá");

        lbHinhAnh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHinhAnh.setForeground(new java.awt.Color(97, 55, 47));
        lbHinhAnh.setText("Hình Ảnh ");

        txtMaDU.setEditable(false);
        txtMaDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDUActionPerformed(evt);
            }
        });

        lbGhiChu.setForeground(new java.awt.Color(97, 55, 47));
        lbGhiChu.setText("Ghi Chú");

        txtGhiChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGhiChuActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resource/delete (1).png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCapNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resource/edit (2).png"))); // NOI18N
        btnCapNhap.setText("Cập Nhập");
        btnCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhapActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resource/refresh-arrow.png"))); // NOI18N
        btnReset.setText("Refresh");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resource/add (1).png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        lbIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIcon.setText("...");
        lbIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lbIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbIconMouseClicked(evt);
            }
        });

        lbInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbInfo.setForeground(new java.awt.Color(97, 55, 47));
        lbInfo.setText("THÔNG TIN ĐỒ UỐNG");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMaDU)
                            .addComponent(lbTenDU)
                            .addComponent(lbGia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbGhiChu)
                            .addComponent(lbHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenDU, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaDU, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(lbInfo)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCapNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbInfo)
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaDU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMaDU))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTenDU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTenDU)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGia))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGhiChu)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHinhAnh))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tbThongTinDU.setBackground(new java.awt.Color(207, 179, 159));
        tbThongTinDU.setForeground(new java.awt.Color(51, 34, 25));
        tbThongTinDU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Đồ Uống ", "Tên Đồ Uống ", "Giá ", "Ghi Chú"
            }
        ));
        tbThongTinDU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThongTinDUMouseClicked(evt);
            }
        });
        tbThongTinDU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbThongTinDUKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbThongTinDU);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
DefaultTableModel modelThongTinDU;

    public void loadTable() {
        modelThongTinDU = new DefaultTableModel();
        String tieuDe[] = {ID, NAME, PRICE, NOTE};
        modelThongTinDU.setColumnIdentifiers(tieuDe);
        Object row[] = new Object[4];
        DoUongController.getInstance().LayDuLieu();
        int i = 0;
        while (i < DataContext.getInstance().getDoUongs().size()) {
            try {
                row[0] = DataContext.getInstance().getDoUongs().get(i).getMaDU();
                row[1] = DataContext.getInstance().getDoUongs().get(i).getTenDU();
                row[2] = DataContext.getInstance().getDoUongs().get(i).getGia();
                row[3] = DataContext.getInstance().getDoUongs().get(i).getGhiChu();
                i++;
                modelThongTinDU.addRow(row);
            } catch (Exception e) {
            }
        }
        tbThongTinDU.setModel(modelThongTinDU);
        setVisible(true);
    }

    public String checkError() {
        if (txtTenDU.getText().equals("")) {
            return ERR_NAME_EMPTY;
        }
        if (txtGia.getText().equals("")) {
            return ERR_PRICE_EMPTY;
        }
        return "";
    }
    private void tbThongTinDUKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbThongTinDUKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbThongTinDUKeyPressed

    private void tbThongTinDUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThongTinDUMouseClicked
        try {
            int row = this.tbThongTinDU.getSelectedRow();
            if (row >= 0 && row <= tbThongTinDU.getRowCount()) {
                txtMaDU.setText(tbThongTinDU.getValueAt(row, 0).toString());
                txtTenDU.setText(tbThongTinDU.getValueAt(row, 1).toString());
                txtGia.setText(tbThongTinDU.getValueAt(row, 2).toString());
                txtGhiChu.setText(tbThongTinDU.getValueAt(row, 3).toString());
                Image img = DataContext.getInstance()
                        .getDoUongs()
                        .stream()
                        .filter(du -> du.getMaDU()
                        == Integer.parseInt(tbThongTinDU.getValueAt(row, 0).toString())
                        ).findFirst().get().getHinhAnh();
                if (img != null) {
                    lbIcon.setIcon(new ImageIcon(ImageHandle.getInstance().resize(
                            img,
                            lbIcon.getWidth(),
                            lbIcon.getHeight()
                    )));
                } else {
                    lbIcon.setIcon(null);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbThongTinDUMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtMaDU.setText("");
        txtTenDU.setText("");
        txtGia.setText("");
        txtGhiChu.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhapActionPerformed
        var x = checkError();
        if (!x.equals("")) {
            JOptionPane.showConfirmDialog(null, x, NOTIFICATION_TITLE, JOptionPane.DEFAULT_OPTION);
            return;
        }
        try {
            DoUongModel doUongModel = new DoUongModel();
            doUongModel.setTenDU(txtTenDU.getText());
            doUongModel.setGia(Double.parseDouble(txtGia.getText()));
            doUongModel.setGhiChu(txtGhiChu.getText());

            if (DoUongController.getInstance().SuaDoUong(Integer.parseInt(txtMaDU.getText()), doUongModel) == true) {
                JOptionPane.showMessageDialog(this, NOTI_SUCCESS, NOTIFICATION_TITLE, JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, NOTI_FAILED, NOTIFICATION_TITLE, JOptionPane.INFORMATION_MESSAGE);
            }
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, NOTI_FAILED, NOTIFICATION_TITLE, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCapNhapActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (this.txtMaDU.getText().equals(""))
            JOptionPane.showMessageDialog(null, CHOSSE_DELETE, NOTIFICATION_TITLE, 1);
        else {
            try {
                int result = JOptionPane.showConfirmDialog(this, REQUEST_DELETE, NOTIFICATION_TITLE, JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    if (DoUongController.getInstance().XoaDoUong(Integer.parseInt(txtMaDU.getText().trim()))) {
                        JOptionPane.showMessageDialog(this, NOTI_SUCCESS, NOTIFICATION_TITLE, JOptionPane.WARNING_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, NOTI_FAILED, NOTIFICATION_TITLE, JOptionPane.WARNING_MESSAGE);
                    }
                }
                loadTable();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, NOTI_FAILED, NOTIFICATION_TITLE, JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        var x = checkError();
        if (!x.equals("")) {
            JOptionPane.showConfirmDialog(null, x, NOTIFICATION_TITLE, JOptionPane.DEFAULT_OPTION);
            return;
        }
        try {
            DoUongModel doUongModel = new DoUongModel();
            doUongModel.setTenDU(txtTenDU.getText());
            doUongModel.setGhiChu(txtGhiChu.getText());
            doUongModel.setGia(Double.parseDouble(txtGia.getText()));
            if (URL != null) {
                doUongModel.setHinhAnh((new ImageIcon(URL)).getImage());
            }
            if (DoUongController.getInstance().ThemDoUong(doUongModel)) {
                JOptionPane.showMessageDialog(this, NOTI_SUCCESS, NOTIFICATION_TITLE, JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, NOTI_FAILED, NOTIFICATION_TITLE, JOptionPane.INFORMATION_MESSAGE);
            }
            loadTable();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, NOTI_FAILED, NOTIFICATION_TITLE, JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void txtGhiChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChuActionPerformed

    private void txtMaDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDUActionPerformed

    private void lbIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconMouseClicked
        try {
            // Lấy ảnh từ máy
            JFileChooser f = new JFileChooser();
            f.showOpenDialog(null);
            f.setDialogTitle(CHOSSE_FILE);
            File fileImg = f.getSelectedFile();
            URL = fileImg.getAbsolutePath();
            //Xử lí ảnh
            System.out.println(URL);
            if (URL != null) {
                Image img = ImageHandle.getInstance().readImage2(URL);
                img = ImageHandle.getInstance().resize(img, 100, 100);
                lbIcon.setIcon(new ImageIcon(img));
                lbIcon.setText("");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lbIconMouseClicked

    //Text
    private String TITLE;
    private String UPDATE;
    private String RESET;
    private String EXIT;
    private String REFRESH;
    private String DELETE;
    private String NOTE;
    private String PRICE;
    private String IMAGE;
    private String INFO;
    private String ID;
    private String NAME;
    private String ERR_NAME_EMPTY;
    private String ERR_PRICE_EMPTY;
    private String NOTIFICATION_TITLE;
    private String NOTI_SUCCESS;
    private String NOTI_FAILED;
    private String CHOSSE_DELETE;
    private String REQUEST_DELETE;
    private String CHOSSE_FILE;
    private String URL;
    private String ADD;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhap;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbGhiChu;
    private javax.swing.JLabel lbGia;
    private javax.swing.JLabel lbHinhAnh;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbMaDU;
    private javax.swing.JLabel lbTenDU;
    private javax.swing.JTable tbThongTinDU;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaDU;
    private javax.swing.JTextField txtTenDU;
    // End of variables declaration//GEN-END:variables
}
